#este programa define la estructura de la configuracion
#se va a generar un mapa de mapas y las propiedades de los mapas

#esta es una llave
news_sites:
    #esta es una 2da llave
    eluniversal:
        url: http://www.eluniversal.com.mx
        queries:
            homepage_article_links: '.field-content a'
            article_body: '.field-name-body'
            article_title: '.pane-content h1'
    elpais:
        url: https://elpais.com
        queries:
            homepage_article_links: '.articulo-titulo a'
            article_body: '.articulo-cuerpo'
            article_title: '.articulo-titulares h1'
    